package com.xbyrh.repo.entity;

import java.util.Date;

public class DeviceUserRef {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_user_ref.id
     *
     * @mbggenerated Fri Apr 16 14:15:51 CST 2021
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_user_ref.device_id
     *
     * @mbggenerated Fri Apr 16 14:15:51 CST 2021
     */
    private Long deviceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_user_ref.uid
     *
     * @mbggenerated Fri Apr 16 14:15:51 CST 2021
     */
    private Long uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_user_ref.is_delete
     *
     * @mbggenerated Fri Apr 16 14:15:51 CST 2021
     */
    private Integer isDelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_user_ref.create_time
     *
     * @mbggenerated Fri Apr 16 14:15:51 CST 2021
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_user_ref.update_time
     *
     * @mbggenerated Fri Apr 16 14:15:51 CST 2021
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_user_ref.id
     *
     * @return the value of device_user_ref.id
     *
     * @mbggenerated Fri Apr 16 14:15:51 CST 2021
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_user_ref.id
     *
     * @param id the value for device_user_ref.id
     *
     * @mbggenerated Fri Apr 16 14:15:51 CST 2021
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_user_ref.device_id
     *
     * @return the value of device_user_ref.device_id
     *
     * @mbggenerated Fri Apr 16 14:15:51 CST 2021
     */
    public Long getDeviceId() {
        return deviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_user_ref.device_id
     *
     * @param deviceId the value for device_user_ref.device_id
     *
     * @mbggenerated Fri Apr 16 14:15:51 CST 2021
     */
    public void setDeviceId(Long deviceId) {
        this.deviceId = deviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_user_ref.uid
     *
     * @return the value of device_user_ref.uid
     *
     * @mbggenerated Fri Apr 16 14:15:51 CST 2021
     */
    public Long getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_user_ref.uid
     *
     * @param uid the value for device_user_ref.uid
     *
     * @mbggenerated Fri Apr 16 14:15:51 CST 2021
     */
    public void setUid(Long uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_user_ref.is_delete
     *
     * @return the value of device_user_ref.is_delete
     *
     * @mbggenerated Fri Apr 16 14:15:51 CST 2021
     */
    public Integer getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_user_ref.is_delete
     *
     * @param isDelete the value for device_user_ref.is_delete
     *
     * @mbggenerated Fri Apr 16 14:15:51 CST 2021
     */
    public void setIsDelete(Integer isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_user_ref.create_time
     *
     * @return the value of device_user_ref.create_time
     *
     * @mbggenerated Fri Apr 16 14:15:51 CST 2021
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_user_ref.create_time
     *
     * @param createTime the value for device_user_ref.create_time
     *
     * @mbggenerated Fri Apr 16 14:15:51 CST 2021
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_user_ref.update_time
     *
     * @return the value of device_user_ref.update_time
     *
     * @mbggenerated Fri Apr 16 14:15:51 CST 2021
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_user_ref.update_time
     *
     * @param updateTime the value for device_user_ref.update_time
     *
     * @mbggenerated Fri Apr 16 14:15:51 CST 2021
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}