package com.xbyrh.repo.entity;

import java.util.Date;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_record.id
     *
     * @mbggenerated Fri Apr 16 14:10:38 CST 2021
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_record.uid
     *
     * @mbggenerated Fri Apr 16 14:10:38 CST 2021
     */
    private Long uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_record.nick_name
     *
     * @mbggenerated Fri Apr 16 14:10:38 CST 2021
     */
    private String nickName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_record.avatar_url
     *
     * @mbggenerated Fri Apr 16 14:10:38 CST 2021
     */
    private String avatarUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_record.openid
     *
     * @mbggenerated Fri Apr 16 14:10:38 CST 2021
     */
    private String openid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_record.create_time
     *
     * @mbggenerated Fri Apr 16 14:10:38 CST 2021
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_record.update_time
     *
     * @mbggenerated Fri Apr 16 14:10:38 CST 2021
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_record.id
     *
     * @return the value of user_record.id
     *
     * @mbggenerated Fri Apr 16 14:10:38 CST 2021
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_record.id
     *
     * @param id the value for user_record.id
     *
     * @mbggenerated Fri Apr 16 14:10:38 CST 2021
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_record.uid
     *
     * @return the value of user_record.uid
     *
     * @mbggenerated Fri Apr 16 14:10:38 CST 2021
     */
    public Long getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_record.uid
     *
     * @param uid the value for user_record.uid
     *
     * @mbggenerated Fri Apr 16 14:10:38 CST 2021
     */
    public void setUid(Long uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_record.nick_name
     *
     * @return the value of user_record.nick_name
     *
     * @mbggenerated Fri Apr 16 14:10:38 CST 2021
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_record.nick_name
     *
     * @param nickName the value for user_record.nick_name
     *
     * @mbggenerated Fri Apr 16 14:10:38 CST 2021
     */
    public void setNickName(String nickName) {
        this.nickName = nickName == null ? null : nickName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_record.avatar_url
     *
     * @return the value of user_record.avatar_url
     *
     * @mbggenerated Fri Apr 16 14:10:38 CST 2021
     */
    public String getAvatarUrl() {
        return avatarUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_record.avatar_url
     *
     * @param avatarUrl the value for user_record.avatar_url
     *
     * @mbggenerated Fri Apr 16 14:10:38 CST 2021
     */
    public void setAvatarUrl(String avatarUrl) {
        this.avatarUrl = avatarUrl == null ? null : avatarUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_record.openid
     *
     * @return the value of user_record.openid
     *
     * @mbggenerated Fri Apr 16 14:10:38 CST 2021
     */
    public String getOpenid() {
        return openid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_record.openid
     *
     * @param openid the value for user_record.openid
     *
     * @mbggenerated Fri Apr 16 14:10:38 CST 2021
     */
    public void setOpenid(String openid) {
        this.openid = openid == null ? null : openid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_record.create_time
     *
     * @return the value of user_record.create_time
     *
     * @mbggenerated Fri Apr 16 14:10:38 CST 2021
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_record.create_time
     *
     * @param createTime the value for user_record.create_time
     *
     * @mbggenerated Fri Apr 16 14:10:38 CST 2021
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_record.update_time
     *
     * @return the value of user_record.update_time
     *
     * @mbggenerated Fri Apr 16 14:10:38 CST 2021
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_record.update_time
     *
     * @param updateTime the value for user_record.update_time
     *
     * @mbggenerated Fri Apr 16 14:10:38 CST 2021
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}