package com.xbyrh.repo.mapper;

import com.xbyrh.repo.entity.DeviceUserRef;
import com.xbyrh.repo.entity.DeviceUserRefExample;
import java.util.List;

public interface DeviceUserRefMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_user_ref
     *
     * @mbggenerated Fri Apr 16 14:15:51 CST 2021
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_user_ref
     *
     * @mbggenerated Fri Apr 16 14:15:51 CST 2021
     */
    int insert(DeviceUserRef record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_user_ref
     *
     * @mbggenerated Fri Apr 16 14:15:51 CST 2021
     */
    int insertSelective(DeviceUserRef record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_user_ref
     *
     * @mbggenerated Fri Apr 16 14:15:51 CST 2021
     */
    List<DeviceUserRef> selectByExample(DeviceUserRefExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_user_ref
     *
     * @mbggenerated Fri Apr 16 14:15:51 CST 2021
     */
    DeviceUserRef selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_user_ref
     *
     * @mbggenerated Fri Apr 16 14:15:51 CST 2021
     */
    int updateByPrimaryKeySelective(DeviceUserRef record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_user_ref
     *
     * @mbggenerated Fri Apr 16 14:15:51 CST 2021
     */
    int updateByPrimaryKey(DeviceUserRef record);
}