package com.xbyrh.repo.mapper;

import com.xbyrh.repo.entity.VideoLog;
import com.xbyrh.repo.entity.VideoLogExample;
import java.util.List;

public interface VideoLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_log
     *
     * @mbggenerated Fri Apr 16 14:10:38 CST 2021
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_log
     *
     * @mbggenerated Fri Apr 16 14:10:38 CST 2021
     */
    int insert(VideoLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_log
     *
     * @mbggenerated Fri Apr 16 14:10:38 CST 2021
     */
    int insertSelective(VideoLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_log
     *
     * @mbggenerated Fri Apr 16 14:10:38 CST 2021
     */
    List<VideoLog> selectByExample(VideoLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_log
     *
     * @mbggenerated Fri Apr 16 14:10:38 CST 2021
     */
    VideoLog selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_log
     *
     * @mbggenerated Fri Apr 16 14:10:38 CST 2021
     */
    int updateByPrimaryKeySelective(VideoLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_log
     *
     * @mbggenerated Fri Apr 16 14:10:38 CST 2021
     */
    int updateByPrimaryKey(VideoLog record);
}